name: cd-deploy-staging

on:
  push:
    branches:
      - 'staging'

jobs:
  deploy-staging:
    # skip if the event is triggered by the release-please-bot pushing branch (for opening a PR to main)
    if: ${{ !contains(github.ref, 'release') }}

    runs-on: "ubuntu-latest"

    steps:
      - name: Import Vault secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://vault.instill.tech
          method: approle
          roleId: ${{ secrets.vaultAppRoleRoleId }}
          secretId: ${{ secrets.vaultAppRoleSecretId }}
          tlsSkipVerify: false
          extraHeaders: |
            CF-Access-Client-Id: ${{ secrets.cfAccessClientId }}
            CF-Access-Client-Secret: ${{ secrets.cfAccessClientSecret }}
          secrets: |
            secret/data/devops/slack/github-action/slack-notify-build bot-token | SLACK_BOT_TOKEN ;
            secret/data/devops/vercel/github-action/product-website-id | PRODUCT_WEBSITE_ID ;
            secret/data/devops/vercel/github-action/vercel-org-id | VERCEL_ORG_ID ; 
            secret/data/devops/vercel/github-action/vercel-token | VERCEL_TOKEN ;

      - name: Notify Slack starting
        if: always()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel: msg-github-action
          status: STARTING
          color: warning

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview

      - name: deploy-to-vercel-staging
        id: deployToVercelStaging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
        
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: msg-github-action
          status: SUCCESS
          color: good

      - name: Notify Slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: msg-github-action
          status: FAILED
          color: danger
