name: cd-build-test-staging

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Lint
        run: yarn lint

  testUnit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Run unit test
        run: yarn test

  deployToStaging:
    if: ${{ !contains(github.ref, 'release') }}
    runs-on: ubuntu-latest
    needs: [lint, testUnit]
    steps:
      - name: Import Vault secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://vault.instill.tech
          method: approle
          roleId: ${{ secrets.vaultAppRoleRoleId }}
          secretId: ${{ secrets.vaultAppRoleSecretId }}
          tlsSkipVerify: false
          extraHeaders: |
            CF-Access-Client-Id: ${{ secrets.cfAccessClientId }}
            CF-Access-Client-Secret: ${{ secrets.cfAccessClientSecret }}
          secrets: |
            secret/data/devops/vercel/github-action product-website-id | PRODUCT_WEBSITE_ID ;
            secret/data/devops/vercel/github-action vercel-org-id | VERCEL_ORG_ID ;
            secret/data/devops/vercel/github-action vercel-token | VERCEL_TOKEN ;
            secret/data/devops/github/drop@instill.tech/github-action personal-access-token | GITHUB_TOKEN ;

      - name: Activate deployment status
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ steps.secrets.outputs.GITHUB_TOKEN }}
          env: preview

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to staging
        id: deployToVercelStaging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ steps.secrets.outputs.VERCEL_TOKEN }}
          github-token: ${{ steps.secrets.outputs.GITHUB_TOKEN }}
          vercel-org-id: ${{ steps.secrets.outputs.VERCEL_ORG_ID }}
          vercel-project-id: ${{ steps.secrets.outputs.PRODUCT_WEBSITE_ID}}
          scope: ${{ steps.secrets.outputs.VERCEL_ORG_ID }}
          github-comment: false
          alias-domains: |
            www.instill-inc.tech

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  deployToStorybook:
    if: ${{ !contains(github.ref, 'release') }}
    runs-on: ubuntu-latest
    needs: [lint, testUnit]
    steps:
      - name: Import Vault secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://vault.instill.tech
          method: approle
          roleId: ${{ secrets.vaultAppRoleRoleId }}
          secretId: ${{ secrets.vaultAppRoleSecretId }}
          tlsSkipVerify: false
          extraHeaders: |
            CF-Access-Client-Id: ${{ secrets.cfAccessClientId }}
            CF-Access-Client-Secret: ${{ secrets.cfAccessClientSecret }}
          secrets: |
            secret/data/devops/vercel/github-action product-webasite-storybook-id | PRODUCT_WEBSITE_STORYBOOK_ID ;
            secret/data/devops/vercel/github-action vercel-org-id | VERCEL_ORG_ID ;
            secret/data/devops/vercel/github-action vercel-token | VERCEL_TOKEN ;
            secret/data/devops/github/drop@instill.tech/github-action personal-access-token | GITHUB_TOKEN ;

      - name: Checkout
        uses: actions/checkout@v3

      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ steps.secrets.outputs.GITHUB_TOKEN }}
          env: preview

      - name: Deploy storybook to vercel
        id: deployStorybookToVercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ steps.secrets.outputs.VERCEL_TOKEN }}
          github-token: ${{ steps.secrets.outputs.GITHUB_TOKEN }}
          vercel-org-id: ${{ steps.secrets.outputs.VERCEL_ORG_ID }}
          vercel-project-id: ${{ steps.secrets.outputs.PRODUCT_WEBSITE_STORYBOOK_ID}}
          scope: ${{ steps.secrets.outputs.VERCEL_ORG_ID }}
          vercel-args: "--prod"
          github-comment: true

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
