name: ci-unit-test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  unit-test:
    # skip the test of release bot opened PR to main
    if: ${{ !contains(github.ref, 'release') }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      # - name: Cache node_modules
      #   uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      # - name: Run tests
      #  run: npm run test
      
      # Depend on the test result file
      # - name: Publish Unit Test Results
      #  uses: EnricoMi/publish-unit-test-result-action@v1
      #  if: always()
      #  with:
      #    files: test-results/**/*.xml