name: Lighthouse Performance

on:
  pull_request:
    branches:
      - "main"

jobs:
  check-main-lighthouse-score:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: deploy main to vercel
        id: deployMainToVercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCELTOKEN }}
          github-token: ${{ secrets.BOTGITHUBTOKEN }}
          vercel-org-id: ${{ secrets.VERCELORGID }}
          vercel-project-id: ${{ secrets.INSTILLTECHVERCELPROJECTID}}
          scope: ${{ secrets.VERCELORGID }}
          github-comment: false

      - name: Create temporary folder for artifacts
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Audit
        id: audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ steps.deployMainToVercel.outputs.preview-url }}
          budgetPath: ./lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts

      - name: Post Summary
        run: pnpm run post-lighthouse-summary-on-ci -- ${{steps.audit.outputs.manifest}}
