name: Lighthouse Performance

on:
  pull_request:
    branches:
      - "main"

jobs:
  check-main-lighthouse-score:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: rm -rf node_modules && pnpm i --frozen-lockfile

      - name: deploy main to vercel
        id: deployMainToVercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCELTOKEN }}
          github-token: ${{ secrets.BOTGITHUBTOKEN }}
          vercel-org-id: ${{ secrets.VERCELORGID }}
          vercel-project-id: ${{ secrets.INSTILLTECHVERCELPROJECTID}}
          scope: ${{ secrets.VERCELORGID }}
          github-comment: false

      - name: Create temporary folder for artifacts
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Audit
        id: audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ steps.deployMainToVercel.outputs.preview-url }}
          budgetPath: ./lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts

      - name: Post Summary
        run: pnpm run post-lighthouse-summary-on-ci -- ${{steps.audit.outputs.manifest}}
